# fast
fast:
  # 是否开启接口文档
  swagger-open: true
  # 加密秘钥
  jwt-secret: f4e2e52034348f86b67cde581c0f9eb5
  # token有效时长，7天，单位秒
  jwt-expire: 604800

# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  connection-timeout: 5000ms
  servlet:
    context-path: /
    session:
      timeout: 3600

# Spring
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  resources:
    add-mappings: false

# mybatis
mybatis-plus:
  mapper-locations: classpath*:com/gitile/example/**/mapper/xml/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.gitile.example.modules.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    #开启驼峰命名转换
    map-underscore-to-camel-case: false
    #配置的缓存的全局开关
    cache-enabled: true 
    #延时加载的开关
    lazyLoadingEnabled: true 
    #是否允许单一语句返回多结果集
    multipleResultSetsEnabled: true 
    #打印sql语句,调试用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  path: logs/
  file: fast-web-example.log